package com.martimlima.springcourse.securitymodule.userregistrationformwithcustomroles.config;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class SecurityWebApplicationInitializer extends AbstractSecurityWebApplicationInitializer {

}
